name: Build PDF on merge to main

on:
  push:
    branches:
      - initial-ver1

jobs:
  build-toc-and-pdf:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Add Table of Contents and Build PDF
        run: |
          yarn markdown-toc -i README.md

          cd H-sfx-EN
          yarn markdown-toc -i README.md
          sed '/<!--/,/-->/d' README.md > temp.md 
          markdown-pdf temp.md -o H-SFX-English-Groupings.pdf 
          rm temp.md

      - name: Add TOC and PDF to Git
        run: |
          git add -- README.md **/README.md
          git add H-sfx-EN/H-SFX-English-Groupings.pdf

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automation generated Table of Contents and rendered PDFs for commit hash '$GITHUB_SHA'"
  