name: Build PDF on merge to main

on:
  push:
    branches:
      - initial-ver1

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Add Table of Contents and Build PDF
        run: |
          yarn markdown-toc -i README.md
          yarn markdown-pdf H-sfx-EN/README.md -o H-sfx-EN/H-SFX-English-Groupings.pdf

      - name: Commit PDF
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add README.md
          git add H-sfx-EN/H-SFX-English-Groupings.pdf
          git commit -m "Automation generated Table of Contents and rendered PDFs for commit hash '$GITHUB_SHA'"
          git push